// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_stream from "./routes/api/stream.ts";
import * as $api_tex_to_svg from "./routes/api/tex-to-svg.ts";
import * as $generate_video from "./routes/generate/video.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $test_canvas from "./routes/test/canvas.tsx";
import * as $test_canvas0 from "./routes/test/canvas0.tsx";
import * as $test_math from "./routes/test/math.tsx";
import * as $test_mathanimation from "./routes/test/mathanimation.tsx";
import * as $test_svg_path from "./routes/test/svg-path.tsx";
import * as $test_visiblemath from "./routes/test/visiblemath.tsx";
import * as $CanvasTest from "./islands/CanvasTest.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MathAnimation from "./islands/MathAnimation.tsx";
import * as $MathCanvas from "./islands/MathCanvas.tsx";
import * as $SVGPathAnimation from "./islands/SVGPathAnimation.tsx";
import * as $SimpleCanvas from "./islands/SimpleCanvas.tsx";
import * as $VideoGenerator from "./islands/VideoGenerator.tsx";
import * as $VisibleMath from "./islands/VisibleMath.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/stream.ts": $api_stream,
    "./routes/api/tex-to-svg.ts": $api_tex_to_svg,
    "./routes/generate/video.tsx": $generate_video,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/test/canvas.tsx": $test_canvas,
    "./routes/test/canvas0.tsx": $test_canvas0,
    "./routes/test/math.tsx": $test_math,
    "./routes/test/mathanimation.tsx": $test_mathanimation,
    "./routes/test/svg-path.tsx": $test_svg_path,
    "./routes/test/visiblemath.tsx": $test_visiblemath,
  },
  islands: {
    "./islands/CanvasTest.tsx": $CanvasTest,
    "./islands/Counter.tsx": $Counter,
    "./islands/MathAnimation.tsx": $MathAnimation,
    "./islands/MathCanvas.tsx": $MathCanvas,
    "./islands/SVGPathAnimation.tsx": $SVGPathAnimation,
    "./islands/SimpleCanvas.tsx": $SimpleCanvas,
    "./islands/VideoGenerator.tsx": $VideoGenerator,
    "./islands/VisibleMath.tsx": $VisibleMath,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
